services:
  streamlit-app:
    build:
      context: ./streamlit_app
      dockerfile: dockerfile
    image: streamlit-dashboard-image
    container_name: streamlit-dashboard-runtime
    volumes:
      - /home/tranm/cert:/certs:ro
    command:
      [
        "streamlit",
        "run",
        "dashboard.py",
        "--server.port=7200",
      ]
    network_mode: host

    env_file:
      - .env 